
CREATE DATABASE Chess_Viewer
GO

USE Chess_Viewer

CREATE TABLE Aberturas (
	Id INT IDENTITY,
	Nome_Abertura VARCHAR(50) NOT NULL,
	Movimentos_Abertura VARCHAR(250) NOT NULL,
	CONSTRAINT PK1 PRIMARY KEY (Id) 
)

CREATE TABLE Partidas (
	Id INT IDENTITY,
	Resultado VARCHAR(3) NOT NULL,
	Evento VARCHAR(50) NOT NULL,
	Website VARCHAR(50),
	DataEvento DATETIME NOT NULL,
	Id_Abertura INT NOT NULL,
	Jogador_Brancas VARCHAR(255) NOT NULL,
	Jogador_Pretas VARCHAR(255) NOT NULL,
	Quantidade_Movimentos VARCHAR(4) NOT NULL,
	Movimentos VARCHAR(4000) NOT NULL,
	CONSTRAINT PK2 PRIMARY KEY CLUSTERED(Id),
	CONSTRAINT FK1 FOREIGN KEY (Id_Abertura) REFERENCES Aberturas(Id)
)

CREATE TABLE Usuario (
	Id INT IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	CONSTRAINT PK3 PRIMARY KEY (Id)
)

CREATE TABLE Jogos_Favoritos (
	Id_Usuario INT,
	Id_Partida INT,
	CONSTRAINT FK2 FOREIGN KEY (Id_Usuario) REFERENCES Usuario(Id),
	CONSTRAINT FK3 FOREIGN KEY (Id_Partida) REFERENCES Partidas(Id)
)

DROP DATABASE Chess_Viewer
